import os
import uuid
import yt_dlp

def normalize_netscape_cookies(content: str) -> str:
    lines = []
    has_header = False
    
    for line in content.splitlines():
        line_strip = line.strip()
        if not line_strip:
            continue
        if line_strip.startswith("#"):
            if "Netscape HTTP Cookie File" in line_strip:
                has_header = True
            lines.append(line_strip)
            continue
            
        # Split by whitespace (in case tabs got converted to spaces)
        fields = line_strip.split()
        if len(fields) == 7:
            lines.append("\t".join(fields))
        else:
            lines.append(line_strip)
            
    if not has_header:
        lines.insert(0, "# Netscape HTTP Cookie File")
        
    return "\n".join(lines)


def download_audio_as_mp3(artist: str, track: str) -> tuple[bytes, str]:
    """
    Search YouTube for the track and artist, download the audio, convert it to MP3,
    and return the file contents (bytes) and the final filename.
    """
    query = f"ytsearch1:{track} {artist}"
    
    # Ensure temporary directory exists inside backend
    temp_dir = os.path.join(os.path.dirname(__file__), "temp_downloads")
    os.makedirs(temp_dir, exist_ok=True)
    
    # Create a unique filename prefix to avoid collisions
    unique_id = str(uuid.uuid4())
    outtmpl = os.path.join(temp_dir, f"{unique_id}.%(ext)s")
    
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': outtmpl,
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        'default_search': 'ytsearch1',
        'noplaylist': True,
        'quiet': True,
        'no_warnings': True,
    }
    
    # Bypass YouTube bot detection by using Netscape format cookies or local browser cookies
    cookies_content = os.environ.get("YOUTUBE_COOKIES", "").strip()
    browser_name = os.environ.get("YOUTUBE_COOKIES_FROM_BROWSER", "").strip()
    
    if cookies_content:
        # Normalize the cookie text structure before saving
        cookies_content = normalize_netscape_cookies(cookies_content)
            
        cookies_path = os.path.join(temp_dir, f"{unique_id}_cookies.txt")
        with open(cookies_path, 'w', encoding='utf-8') as cf:
            cf.write(cookies_content)
        ydl_opts['cookiefile'] = cookies_path
    elif browser_name:
        # Extract cookies from a local browser (e.g. 'chrome', 'firefox', 'edge')
        # Wrapped in a tuple to prevent yt-dlp from unpacking the string as individual characters
        ydl_opts['cookiesfrombrowser'] = (browser_name,)
        
    mp3_path = os.path.join(temp_dir, f"{unique_id}.mp3")
    
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.extract_info(query, download=True)
            
        if not os.path.exists(mp3_path):
            raise FileNotFoundError("MP3 file was not generated by yt-dlp.")
            
        with open(mp3_path, 'rb') as f:
            data = f.read()
            
        # Sanitize filename (remove characters not allowed in filenames)
        safe_title = f"{track} - {artist}"
        for char in ['<', '>', ':', '"', '/', '\\', '|', '?', '*']:
            safe_title = safe_title.replace(char, '')
        filename = f"{safe_title}.mp3"
        
        return data, filename
        
    finally:
        # Clean up any files that match the unique_id in the temp_dir
        if os.path.exists(temp_dir):
            for file in os.listdir(temp_dir):
                if file.startswith(unique_id):
                    try:
                        os.remove(os.path.join(temp_dir, file))
                    except Exception:
                        pass
