import os
import uuid
import yt_dlp

def download_audio_as_mp3(artist: str, track: str) -> tuple[bytes, str]:
    """
    Search YouTube for the track and artist, download the audio, convert it to MP3,
    and return the file contents (bytes) and the final filename.
    """
    query = f"ytsearch1:{track} {artist}"
    
    # Ensure temporary directory exists inside backend
    temp_dir = os.path.join(os.path.dirname(__file__), "temp_downloads")
    os.makedirs(temp_dir, exist_ok=True)
    
    # Create a unique filename prefix to avoid collisions
    unique_id = str(uuid.uuid4())
    outtmpl = os.path.join(temp_dir, f"{unique_id}.%(ext)s")
    
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': outtmpl,
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        'default_search': 'ytsearch1',
        'noplaylist': True,
        'quiet': True,
        'no_warnings': True,
    }
    
    # Bypass YouTube bot detection by using Netscape format cookies from environment
    cookies_content = os.environ.get("YOUTUBE_COOKIES", "").strip()
    if cookies_content:
        # Netscape format requires a specific header line to be recognized by yt-dlp
        if not cookies_content.startswith("# Netscape"):
            cookies_content = "# Netscape HTTP Cookie File\n" + cookies_content
            
        cookies_path = os.path.join(temp_dir, f"{unique_id}_cookies.txt")
        with open(cookies_path, 'w', encoding='utf-8') as cf:
            cf.write(cookies_content)
        ydl_opts['cookiefile'] = cookies_path
        
    mp3_path = os.path.join(temp_dir, f"{unique_id}.mp3")
    
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.extract_info(query, download=True)
            
        if not os.path.exists(mp3_path):
            raise FileNotFoundError("MP3 file was not generated by yt-dlp.")
            
        with open(mp3_path, 'rb') as f:
            data = f.read()
            
        # Sanitize filename (remove characters not allowed in filenames)
        safe_title = f"{track} - {artist}"
        for char in ['<', '>', ':', '"', '/', '\\', '|', '?', '*']:
            safe_title = safe_title.replace(char, '')
        filename = f"{safe_title}.mp3"
        
        return data, filename
        
    finally:
        # Clean up any files that match the unique_id in the temp_dir
        if os.path.exists(temp_dir):
            for file in os.listdir(temp_dir):
                if file.startswith(unique_id):
                    try:
                        os.remove(os.path.join(temp_dir, file))
                    except Exception:
                        pass
